ARG REPO=golang
FROM $REPO:alpine

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN addgroup --gid $USER_GID $USERNAME \
    && adduser --uid $USER_UID --ingroup $USERNAME --home /home/$USERNAME --shell /bin/sh --disabled-password --gecos "" $USERNAME

RUN apk update \
    && apk upgrade --no-cache \
    && rm -rf /var/cache/apk/*

